#include "trackprotocolswidget.h"
// This header is generated by uic from your .ui file
#include "ui_trackprotocolswidget.h"

TrackProtocolsWidget::TrackProtocolsWidget(QWidget *parent)
    : QWidget(parent)
    , ui(new Ui::TrackProtocolsWidget)
{
    ui->setupUi(this);
}

TrackProtocolsWidget::~TrackProtocolsWidget()
{
    delete ui;  // Proper cleanup
}
