CREATE TABLE EQUIPMENT (
  ID_EQUIPMENT     VARCHAR2(20 BYTE)    NOT NULL,
  NAME             VARCHAR2(100 BYTE),
  TYPE             VARCHAR2(50 BYTE),
  STATUS           VARCHAR2(50 BYTE),
  MAINTENANCE_DATE DATE,
  QUANTITY         NUMBER,
  PURCHASE_DATE    DATE,
  INITIAL_PRICE    NUMBER,
  DANGEROUS        VARCHAR2(10 BYTE),
  CONSUMABLE       VARCHAR2(10 BYTE),
  CONSTRAINT PK_EQUIPMENT PRIMARY KEY (ID_EQUIPMENT)
);
