CREATE TABLE PATIENT (
  ID_PATIENT   NUMBER(38,0)          NOT NULL,
  NAME         VARCHAR2(100 BYTE)    NOT NULL,
  PRENAME      VARCHAR2(100 BYTE)    NOT NULL,
  EMAIL        VARCHAR2(255 BYTE),
  QR_IMAGE     BLOB,
  QR_DATA      VARCHAR2(255 BYTE),
  CONSTRAINT PK_PATIENT PRIMARY KEY (ID_PATIENT)
);
